### ISSUE TITLE
ETC account/address created with emerald dose not show/sync in transactions

### ISSUE THREAD

**Issue by teknowill** [ETCDEVTeam/emerald-wallet#655]
in bound @ block 6 043 578 of 1.007 etc
the windows 10 emerald wallet is full node synced at block 6 045 787
i created the address with emerald wallet

https://gastracker.io/tx/0x2863385e1b916c6493546ba0874afa72d56b79f987a63fa3d3dec99c4a4ab658
@ 6/22/18 4:18 AM

http://gastracker.io/addr/0x70b18c9c0ad118ff77755546c83650519a6ca86a 

not sure why emerald does not show or update the balance / history.
maybe i am doing something wrong
thanks
![2018-06-22_13-05-38](https://user-images.githubusercontent.com/7273509/41789425-41a13844-761d-11e8-82a4-e0673e23a914.png)

**Comment by shanejonas** [comment]
I believe this is solved in the upcoming release.

related to #648

**Comment by teknowill** [comment]
looks like the same thing. Didn't know if myethwallet was something specific, will look out for next release, thanks.

Really like the wallet otherwise, no contest that works much better then eths.
not sure if this is the place for suggestions / feature requests or what is already planned but it would be cool if 

- it could export transaction history as a CSV or json file
- the wallet or gastracker API worked with portfolio sites like cointracking.info etc to help with taxes and keeping track of everything across wallets/coins
- gas limit / fee had up/down or ruff time option, could select a ruff estimated transaction time and fee you are willing/need to pay based on current difficulty/load. 
- during install or after you could, as a full node tell it to store the blockchaindata on a separate drive or network drive to save space on your boot drive.

**Comment by BelfordZ** [comment]
Thanks @teknowill. You can make issue tickets with feature suggestions as well. 

I like 1 & 4

**Comment by teknowill** [comment]
will do thanks! upgraded to 1.0 still no balance, tx history shows most recent and back till 6/27/18 but nothing before, which there were two others going back till 6/22/18. windows 10 pro v1709 64bit.  I installed with option everyone vs just me. if that helps any, might be the anomaly.  You do have to elevate to run as admin on first run, even if a windows admin if you select run on everyone or it can't download/write to files it's trying to load. after I get no errors and do not need to elevate. elevated or not, no difference on balance or history or sync behavior.  

![2018-06-29_12-42-26](https://user-images.githubusercontent.com/7273509/42104282-fa9663de-7b99-11e8-805b-8b278d8964b2.png)

**Comment by teknowill** [comment]
all the transactions do show up eventually, but the account total never updates, still shows 0.
Keep getting failed to fetch and the not connected to synced node. When you close / open the block count is higher, so i just leave it open with the bug message to keep the node up. 
![2018-07-06_13-20-11](https://user-images.githubusercontent.com/7273509/42392120-b8e93c00-811f-11e8-97b4-10e65f7feb7f.png)
https://github.com/ETCDEVTeam/emerald-wallet/issues/681

**Comment by teknowill** [comment]
Just kept letting it run. Today I closed and opened the wallet. 
The account total updated to show the correct amount. 
The transaction history also accurately reflects the ledger history.
So the history and total issue seem to be confirmed fixed with version 1 for me anyway, thanks!


![2018-07-10_20-15-22](https://user-images.githubusercontent.com/7273509/42544597-c6777e5e-8480-11e8-980b-1ad5516a538f.png)


i do still keep getting the occasional : 
You are not connected to not synced node. your balances can show wrong value. about xxxx block left.
this comes and goes. It is hard understand what it means.

English replacement suggestions, depending on what is meant: 
You are connected to a node that is not fully synchronized, balances may be inaccurate. 
You are not connected to any other node(s). Your wallet is out of sync with the network. It may not reflect current values. or just:  Your wallet is out of sync with the network. It may not reflect current values.

**Comment by BelfordZ** [comment]
Thanks for the update on your issue. Much appreciated. Glad you are enjoying the 1.0 release. 

Also, that is a great suggestion. Would you mind making a separate issue for this wording concern, so that we may close this one?
